### ISSUE TITLE
pylon run problem

### ISSUE THREAD

**Issue by ErenYeager80** [nexus-stc/hyperboria#51]
Hi,
I tried to run pylon with command :

bazel run -c opt cli -- doi 10.1056/NEJMoa2033700 --output article.pdf

But I got this error:
INFO: Analyzed target //nexus/pylon:cli (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //nexus/pylon:cli up-to-date:
  bazel-bin/nexus/pylon/cli
INFO: Elapsed time: 0.525s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
ERROR: Cannot find key: doi
Usage: cli.py <command>
  available commands:    download

For detailed information on this command, run:
  cli.py --help

After that I tried:
bazel run -c opt cli download -- doi 10.1056/NEJMoa2033700 --output article.pdf

but i still get error like this:

INFO: Analyzed target //nexus/pylon:cli (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //nexus/pylon:cli up-to-date:
  bazel-bin/nexus/pylon/cli
INFO: Elapsed time: 0.192s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
File not found
ERROR: Could not consume arg: 10.1056/NEJMoa2033700
Usage: cli.py download doi 10.1056/NEJMoa2033700 --output -

For detailed information on this command, run:
  cli.py download doi 10.1056/NEJMoa2033700 --output - --help

**Comment by the-superpirate** [comment]
I have synchronized sources and updated docs for `pylon`. Let me know if issues would remain!
