### ISSUE TITLE
How/Where/Should I integrate my project into this repository ? 

### ISSUE THREAD

**Issue by Galz648** [nexus-stc/hyperboria#54]
I'm working on a project which integrates library genesis with a chat bot. the point of this project is to at some point create a decentralized service that provides text embeddings

Would love to create a discussion about your visions with this repository. I also believe that the sub repositories should have documentation relating to the solution and functionality it provides

**Comment by the-superpirate** [comment]
@Galz648 hi! I believe you understand that what is you are going to do is related to piracy, an activity that qualified as a prosecutable crime in most countries. So my first advice before any discussions will be to change your account to the anonymous one.

Secondly, this repository is a collection of scripts that is not supposed to be launched as a stand-alone platform. You should be an advanced Python developer to find out how to use it or develop your own scripts. There is no any readable documentation, but if you will write one, I'm happily merge it to the repository.
